# Import Libraries

In [1]:
import numpy as np
import pandas as pd

# Import Data

In [2]:
# Import data.
loan_data_preprocessed_backup = pd.read_csv('loan_data_2007_2014_preprocessed.csv')

C:\Users\dcgzb\AppData\Local\Temp\ipykernel_19452\52255634.py:2: DtypeWarning: Columns (21,49) have mixed types. Specify dtype option on import or set low_memory=False.
  loan_data_preprocessed_backup = pd.read_csv('loan_data_2007_2014_preprocessed.csv')

# Explore Data

In [3]:
loan_data_preprocessed = loan_data_preprocessed_backup.copy()

In [4]:
loan_data_preprocessed.columns.values
# Displays all column names.

array(['Unnamed: 0.1', 'Unnamed: 0', 'id', 'member_id', 'loan_amnt',
       'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length',
       'home_ownership', 'annual_inc', 'verification_status', 'issue_d',
       'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose', 'title',
       'zip_code', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
       'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
       'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'emp_length_int', 'earliest_cr_line_date',
       'mths_since_earliest_cr_line', 'term_int', 'issue_d_date',
       'mths_since_issue_d', 'grade:A', 'grade:B', 'grade:C', 'grade:D',
       'grade:E', 'grade:F', 'grade:G', 'sub_grade:A1', 'sub_grade:A2',
       'sub_grade:A3', 'sub_grade:A4', 'sub_grade:A5', 'sub_grade:B1',
       'sub_grade:B2', 'sub_grade:B3', 'sub_grade:B4', 'sub_grade:B5',
       'sub_grade:C1', 'sub_grade:C2', 'sub_grade:C3', 'sub_grade:C4',
       'sub_grade:C5', 'sub_grade:D1', 'sub_grade:D2', 'sub_grade:D3',
       'sub_grade:D4', 'sub_grade:D5', 'sub_grade:E1', 'sub_grade:E2',
       'sub_grade:E3', 'sub_grade:E4', 'sub_grade:E5', 'sub_grade:F1',
       'sub_grade:F2', 'sub_grade:F3', 'sub_grade:F4', 'sub_grade:F5',
       'sub_grade:G1', 'sub_grade:G2', 'sub_grade:G3', 'sub_grade:G4',
       'sub_grade:G5', 'home_ownership:ANY', 'home_ownership:MORTGAGE',
       'home_ownership:NONE', 'home_ownership:OTHER',
       'home_ownership:OWN', 'home_ownership:RENT',
       'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Does not meet the credit policy. Status:Charged Off',
       'loan_status:Does not meet the credit policy. Status:Fully Paid',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Late (16-30 days)', 'loan_status:Late (31-120 days)',
       'purpose:car', 'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:educational', 'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:IA', 'addr_state:ID', 'addr_state:IL', 'addr_state:IN',
       'addr_state:KS', 'addr_state:KY', 'addr_state:LA', 'addr_state:MA',
       'addr_state:MD', 'addr_state:ME', 'addr_state:MI', 'addr_state:MN',
       'addr_state:MO', 'addr_state:MS', 'addr_state:MT', 'addr_state:NC',
       'addr_state:NE', 'addr_state:NH', 'addr_state:NJ', 'addr_state:NM',
       'addr_state:NV', 'addr_state:NY', 'addr_state:OH', 'addr_state:OK',
       'addr_state:OR', 'addr_state:PA', 'addr_state:RI', 'addr_state:SC',
       'addr_state:SD', 'addr_state:TN', 'addr_state:TX', 'addr_state:UT',
       'addr_state:VA', 'addr_state:VT', 'addr_state:WA', 'addr_state:WI',
       'addr_state:WV', 'addr_state:WY', 'initial_list_status:f',
       'initial_list_status:w', 'good_bad'], dtype=object)

In [5]:
loan_data_preprocessed.head()

,Unnamed: 0.1,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,...,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w,good_bad
0,0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,...,0,0,0,0,0,0,0,1,0,1
1,1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,...,0,0,0,0,0,0,0,1,0,0
2,2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,...,0,0,0,0,0,0,0,1,0,1
3,3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,...,0,0,0,0,0,0,0,1,0,1
4,4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,...,0,0,0,0,0,0,0,1,0,1

In [6]:
loan_data_preprocessed.tail()

,Unnamed: 0.1,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,...,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w,good_bad
466280,466280,466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,...,0,0,0,0,0,0,0,0,1,1
466281,466281,466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,...,0,0,0,0,0,0,0,1,0,0
466282,466282,466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,...,0,0,0,0,0,0,0,1,0,1
466283,466283,466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,...,0,0,0,0,0,0,0,0,1,1
466284,466284,466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,...,0,0,0,0,0,0,0,1,0,1

In [7]:
loan_data_defaults = loan_data_preprocessed[loan_data_preprocessed['loan_status'].isin(['Charged Off','Does not meet the credit policy. Status:Charged Off'])]
# Here we take only the accounts that were charged-off (written-off).

In [8]:
loan_data_defaults.shape

(43236, 209)

In [9]:
pd.options.display.max_rows = None
# Sets the pandas dataframe options to display all columns/ rows.

In [10]:
loan_data_defaults.isnull().sum()

Unnamed: 0.1                                                           0
Unnamed: 0                                                             0
id                                                                     0
member_id                                                              0
loan_amnt                                                              0
funded_amnt                                                            0
funded_amnt_inv                                                        0
term                                                                   0
int_rate                                                               0
installment                                                            0
grade                                                                  0
sub_grade                                                              0
emp_title                                                           3287
emp_length                                                          2337
home_ownership                                                         0
annual_inc                                                             0
verification_status                                                    0
issue_d                                                                0
loan_status                                                            0
pymnt_plan                                                             0
url                                                                    0
desc                                                               27396
purpose                                                                0
title                                                                  3
zip_code                                                               0
addr_state                                                             0
dti                                                                    0
delinq_2yrs                                                            0
earliest_cr_line                                                       3
inq_last_6mths                                                         0
mths_since_last_delinq                                             23950
mths_since_last_record                                             37821
open_acc                                                               0
pub_rec                                                                0
revol_bal                                                              0
revol_util                                                            53
total_acc                                                              0
initial_list_status                                                    0
out_prncp                                                              0
out_prncp_inv                                                          0
total_pymnt                                                            0
total_pymnt_inv                                                        0
total_rec_prncp                                                        0
total_rec_int                                                          0
total_rec_late_fee                                                     0
recoveries                                                             0
collection_recovery_fee                                                0
last_pymnt_d                                                         376
last_pymnt_amnt                                                        0
next_pymnt_d                                                       42475
last_credit_pull_d                                                     6
collections_12_mths_ex_med                                            28
mths_since_last_major_derog                                        35283
policy_code                                                            0
application_type                                                       0
annual_inc_joint                                                   43236
dti_joint                                                          43236
verification_status_joint                                          43236
acc_now_delinq                                                         0
tot_coll_amt                                                       10780
tot_cur_bal                                                        10780
open_acc_6m                                                        43236
open_il_6m                                                         43236
open_il_12m                                                        43236
open_il_24m                                                        43236
mths_since_rcnt_il                                                 43236
total_bal_il                                                       43236
il_util                                                            43236
open_rv_12m                                                        43236
open_rv_24m                                                        43236
max_bal_bc                                                         43236
all_util                                                           43236
total_rev_hi_lim                                                       0
inq_fi                                                             43236
total_cu_tl                                                        43236
inq_last_12m                                                       43236
emp_length_int                                                         0
earliest_cr_line_date                                                  3
mths_since_earliest_cr_line                                            0
term_int                                                               0
issue_d_date                                                           0
mths_since_issue_d                                                     0
grade:A                                                                0
grade:B                                                                0
grade:C                                                                0
grade:D                                                                0
grade:E                                                                0
grade:F                                                                0
grade:G                                                                0
sub_grade:A1                                                           0
sub_grade:A2                                                           0
sub_grade:A3                                                           0
sub_grade:A4                                                           0
sub_grade:A5                                                           0
sub_grade:B1                                                           0
sub_grade:B2                                                           0
sub_grade:B3                                                           0
sub_grade:B4                                                           0
sub_grade:B5                                                           0
sub_grade:C1                                                           0
sub_grade:C2                                                           0
sub_grade:C3                                                           0
sub_grade:C4                                                           0
sub_grade:C5                                                           0
sub_grade:D1                                                           0
sub_grade:D2                                                           0
sub_grade:D3                                                           0
sub_grade:D4                                                           0
sub_grade:D5                                                           0
sub_grade:E1                                                           0
sub_grade:E2                                                           0
sub_grade:E3                                                           0
sub_grade:E4                                                           0
sub_grade:E5                                                           0
sub_grade:F1                                                           0
sub_grade:F2                                                           0
sub_grade:F3                                                           0
sub_grade:F4                                                           0
sub_grade:F5                                                           0
sub_grade:G1                                                           0
sub_grade:G2                                                           0
sub_grade:G3                                                           0
sub_grade:G4                                                           0
sub_grade:G5                                                           0
home_ownership:ANY                                                     0
home_ownership:MORTGAGE                                                0
home_ownership:NONE                                                    0
home_ownership:OTHER                                                   0
home_ownership:OWN                                                     0
home_ownership:RENT                                                    0
verification_status:Not Verified                                       0
verification_status:Source Verified                                    0
verification_status:Verified                                           0
loan_status:Charged Off                                                0
loan_status:Current                                                    0
loan_status:Default                                                    0
loan_status:Does not meet the credit policy. Status:Charged Off        0
loan_status:Does not meet the credit policy. Status:Fully Paid         0
loan_status:Fully Paid                                                 0
loan_status:In Grace Period                                            0
loan_status:Late (16-30 days)                                          0
loan_status:Late (31-120 days)                                         0
purpose:car                                                            0
purpose:credit_card                                                    0
purpose:debt_consolidation                                             0
purpose:educational                                                    0
purpose:home_improvement                                               0
purpose:house                                                          0
purpose:major_purchase                                                 0
purpose:medical                                                        0
purpose:moving                                                         0
purpose:other                                                          0
purpose:renewable_energy                                               0
purpose:small_business                                                 0
purpose:vacation                                                       0
purpose:wedding                                                        0
addr_state:AK                                                          0
addr_state:AL                                                          0
addr_state:AR                                                          0
addr_state:AZ                                                          0
addr_state:CA                                                          0
addr_state:CO                                                          0
addr_state:CT                                                          0
addr_state:DC                                                          0
addr_state:DE                                                          0
addr_state:FL                                                          0
addr_state:GA                                                          0
addr_state:HI                                                          0
addr_state:IA                                                          0
addr_state:ID                                                          0
addr_state:IL                                                          0
addr_state:IN                                                          0
addr_state:KS                                                          0
addr_state:KY                                                          0
addr_state:LA                                                          0
addr_state:MA                                                          0
addr_state:MD                                                          0
addr_state:ME                                                          0
addr_state:MI                                                          0
addr_state:MN                                                          0
addr_state:MO                                                          0
addr_state:MS                                                          0
addr_state:MT                                                          0
addr_state:NC                                                          0
addr_state:NE                                                          0
addr_state:NH                                                          0
addr_state:NJ                                                          0
addr_state:NM                                                          0
addr_state:NV                                                          0
addr_state:NY                                                          0
addr_state:OH                                                          0
addr_state:OK                                                          0
addr_state:OR                                                          0
addr_state:PA                                                          0
addr_state:RI                                                          0
addr_state:SC                                                          0
addr_state:SD                                                          0
addr_state:TN                                                          0
addr_state:TX                                                          0
addr_state:UT                                                          0
addr_state:VA                                                          0
addr_state:VT                                                          0
addr_state:WA                                                          0
addr_state:WI                                                          0
addr_state:WV                                                          0
addr_state:WY                                                          0
initial_list_status:f                                                  0
initial_list_status:w                                                  0
good_bad                                                               0
dtype: int64

# Independent Variables

In [11]:
loan_data_defaults['mths_since_last_delinq'].fillna(0, inplace = True)
# We fill the missing values with zeroes.

C:\Users\dcgzb\AppData\Local\Temp\ipykernel_19452\1935142453.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loan_data_defaults['mths_since_last_delinq'].fillna(0, inplace = True)

In [12]:
#loan_data_defaults['mths_since_last_delinq'].fillna(loan_data_defaults['mths_since_last_delinq'].max() + 12, inplace=True)

In [13]:
loan_data_defaults['mths_since_last_record'].fillna(0, inplace=True)
# We fill the missing values with zeroes.

C:\Users\dcgzb\AppData\Local\Temp\ipykernel_19452\4107388959.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loan_data_defaults['mths_since_last_record'].fillna(0, inplace=True)